# Generated by Django 6.0.4 on 2026-04-17 20:41

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artworks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkcomparison',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_comparisons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='artworks.artwork'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='artworks.category'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='artworks.artwork'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['status'], name='artworks_status_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['artist'], name='artworks_artist_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['category'], name='artworks_category_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['price'], name='artworks_price_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='artworks_created_at_brin'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='artworks_search_gin'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user'], name='favorites_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'artwork')},
        ),
    ]
