# Generated by Django 6.0.4 on 2026-04-17 23:50

import artworks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=artworks.models.artist_image_upload_path),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='image',
            field=models.ImageField(upload_to=artworks.models.artwork_image_upload_path),
        ),
    ]
