# Generated by Django 6.0.4 on 2026-04-17 20:41

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservationhistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservationhistory',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='reservations.reservation'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['user', 'status'], name='reservations_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['event', 'status'], name='reservations_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['reserved_at'], name='reservations_reserved_at_brin'),
        ),
        migrations.AddIndex(
            model_name='reservationhistory',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['changed_at'], name='res_history_changed_at_brin'),
        ),
    ]
