# Generated by Django 6.0.4 on 2026-04-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='events.event'),
        ),
    ]
