# Generated by Django 6.0.4 on 2026-04-17 20:41

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='assigned_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='campaigns.campaign'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['is_active'], name='campaigns_active_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['start_date', 'end_date'], name='campaigns_dates_brin'),
        ),
        migrations.AddIndex(
            model_name='coupon',
            index=models.Index(fields=['is_active', 'valid_until'], name='coupons_active_valid_idx'),
        ),
    ]
