# Generated by Django 6.0.4 on 2026-04-17 20:41

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
        ('reservations', '0002_initial'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='reservation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='reservations.reservation'),
        ),
        migrations.AddField(
            model_name='eventreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='artwork_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='reviews.artworkreview'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='event_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='reviews.eventreview'),
        ),
        migrations.AddField(
            model_name='reviewreply',
            name='replied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='artwork_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.artworkreview'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='event_review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reviews.eventreview'),
        ),
        migrations.AddField(
            model_name='reviewvote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='artworkreview',
            index=models.Index(fields=['artwork', 'is_approved'], name='artwork_reviews_artwork_idx'),
        ),
        migrations.AddIndex(
            model_name='artworkreview',
            index=models.Index(fields=['rating'], name='artwork_reviews_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='artworkreview',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='artwork_reviews_created_brin'),
        ),
        migrations.AlterUniqueTogether(
            name='artworkreview',
            unique_together={('user', 'artwork')},
        ),
        migrations.AddIndex(
            model_name='eventreview',
            index=models.Index(fields=['event', 'is_approved'], name='event_reviews_event_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreview',
            index=models.Index(fields=['rating'], name='event_reviews_rating_idx'),
        ),
        migrations.AddIndex(
            model_name='eventreview',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='event_reviews_created_brin'),
        ),
        migrations.AlterUniqueTogether(
            name='eventreview',
            unique_together={('user', 'event')},
        ),
        migrations.AlterUniqueTogether(
            name='reviewvote',
            unique_together={('user', 'artwork_review'), ('user', 'event_review')},
        ),
    ]
