# Generated by Django 6.0.4 on 2026-04-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'support_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('order', 'Sipariş'), ('reservation', 'Rezervasyon'), ('payment', 'Ödeme'), ('artwork', 'Eser'), ('account', 'Hesap'), ('other', 'Diğer')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Açık'), ('in_progress', 'İşlemde'), ('resolved', 'Çözüldü'), ('closed', 'Kapatıldı')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Destek Talebi',
                'verbose_name_plural': 'Destek Talepleri',
                'db_table': 'support_tickets',
            },
        ),
    ]
