# Generated by Django 6.0.4 on 2026-04-17 20:41

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'status'], name='support_tickets_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='support_tickets_created_brin'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='support_messages_created_brin'),
        ),
    ]
