# Generated by Django 6.0.4 on 2026-04-17 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='sup_tickets_user_status_idx',
            old_name='support_tickets_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='supportticket',
            new_name='sup_tickets_created_brin',
            old_name='support_tickets_created_brin',
        ),
    ]
