# Generated by Django 4.2.30 on 2026-05-19 17:45

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_order', 'Yeni Sipariş'), ('new_reservation', 'Yeni Rezervasyon'), ('new_support', 'Yeni Destek Talebi'), ('new_review', 'Yeni Yorum'), ('order_paid', 'Sipariş Ödendi'), ('order_shipped', 'Sipariş Kargoya Verildi'), ('order_delivered', 'Sipariş Teslim Edildi'), ('order_cancelled', 'Sipariş İptal Edildi'), ('reservation_confirmed', 'Rezervasyon Onaylandı'), ('reservation_cancelled', 'Rezervasyon İptal Edildi'), ('support_replied', 'Destek Yanıtı'), ('general', 'Genel')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=300)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('reservation_id', models.IntegerField(blank=True, null=True)),
                ('support_id', models.IntegerField(blank=True, null=True)),
                ('review_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notifs_recipient_read_idx'), django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='notifs_created_at_brin')],
            },
        ),
    ]
